server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-route
          uri: http://httpbin.org:80
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
